CREATE TABLE LMS_MEMBERS
(
    MEMBER_ID VARCHAR(10),
    MEMBER_NAME VARCHAR(30),
    CITY VARCHAR(20),
    DATE_REGISTER DATE,
    DATE_EXPIRE DATE,
    MEMBERSHIP_STATUS VARCHAR(15),
    PRIMARY KEY(MEMBER_ID)
)
