CREATE TABLE LMS_MEMBERS
(
    MEMBER_ID VARCHAR(10),
    MEMBER_NAME VARCHAR(30),
    CITY VARCHAR(20),
    DATE_REGISTER DATE,
    DATE_EXPIRE DATE,
    MEMBERSHIP_STATUS VARCHAR(15),
    PRIMARY KEY(MEMBER_ID)
)
CREATE TABLE LMS_BOOK_DETAILS
(
    BOOK_CODE VARCHAR(10),
    BOOK_TITLE VARCHAR(50),
    CATEGORY VARCHAR(15),
    AUTHOR VARCHAR(30),
    PUBLICATION VARCHAR(30),
    PUBLISH_DATE DATE,
    BOOK_EDITION INT,
    PRICE INT,
    MEMBERSHIP_STATUS VARCHAR(15),
    PRIMARY KEY(MEMBER_ID)
)
