CREATE TABLE LMS_MEMBERS
(
    MEMBER_ID VARCHAR(10),
    MEMBER_NAME VARCHAR(30),
    CITY VARCHAR(20),
    DATE_REGISTER DATE,
    DATE_EXPIRE DATE,
    MEMBERSHIP_STATUS VARCHAR(15),
    PRIMARY KEY(MEMBER_ID)
)
CREATE TABLE LMS_SUPPLIER_DETAILS
(
    SUPPLIER_ID VARCHAR(3),
    SUPPLIER_NAME VARCHAR(30),
    ADDRESS VARCHAR(50),
    CONTACT INT,
    EMAIL VARCHAR(15),
    PRIMARY KEY(SUPPLIER_ID)
)
CREATE TABLE LMS_BOOK_DETAILS
(
    BOOK_CODE VARCHAR(10),
    BOOK_TITLE VARCHAR(50),
    CATEGORY VARCHAR(15),
    AUTHOR VARCHAR(30),
    PUBLICATION VARCHAR(30),
    PUBLISH_DATE DATE,
    BOOK_EDITION INT,
    PRICE INT,
    RACK_NUM VARCHAR(3),
    DATE_ARRIVAL DATE,
    PRIMARY KEY(BOOK_CODE),
    FOREIGN KEY(SUPPLIER_ID) REFERENCES LMS_SUPPLIER_DETAILS(SUPPLIER_ID)
)

CREATE TABLE LMS_FINE_DETAILS
(
    FINE_RANGE VARCHAR(3),
    FINE_AMOUNT INT,
)
